/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * Additional Notes: /Game\s?(\d*):((\s?\d*\s\w+)(,|;|\n))* / seems to be able to select everything 
 * hopefully this can be used to sort into group of id and dice for further processing
 * Further thought maybe simple text functions might be better
 */
package day2;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.commons.lang3.StringUtils;

public class part1 {
    
    public static void main(String[] args) {
        try {
            Properties properties = new Properties();
            properties.load(new FileInputStream("app/src/main/resources/config.properties"));

            FileReader file = new FileReader(properties.getProperty("input"));
            BufferedReader reader = new BufferedReader(file);
            String line;
            int redLimit = 12;
            int greenLimit = 13;
            int blueLimit = 14;
            int total = 0;

            while ((line = reader.readLine()) != null) {
                List<String> splitLine = new ArrayList<>();
                splitLine = Arrays.asList(line.split(":|;|,"));
                Pattern numbersPattern = Pattern.compile("\\d+");

                int game = 0;
                int red = 0;
                int green = 0;
                int blue = 0;
                int invalid = 0;
                for (String str : splitLine) {
                    Matcher numbersMatcher = numbersPattern.matcher(str);
                    if (numbersMatcher.find()) {
                        if (StringUtils.containsIgnoreCase(str, "game")) {
                            game = Integer.parseInt(numbersMatcher.group());
                        }
                        if (StringUtils.containsIgnoreCase(str, "red")) {
                            red = Integer.parseInt(numbersMatcher.group());
                            if (red > redLimit) {
                                invalid = 1;
                            }
                        }
                        if (StringUtils.containsIgnoreCase(str, "green")) {
                            green = Integer.parseInt(numbersMatcher.group());
                            if (green > greenLimit) {
                                invalid = 1;
                            }
                        }
                        if (StringUtils.containsIgnoreCase(str, "blue")) {
                            blue = Integer.parseInt(numbersMatcher.group());
                            if (blue > blueLimit) {
                                invalid = 1;
                            }
                        }
                    }
                }
                if (invalid == 1) {
                    game = 0;
                }
                total += game;
            }
            System.out.println("Total: " + total);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
