/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day3;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        part1 classUnderTest = new part1();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
